//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxySignage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public Video()
        {
            this.Playlists = new HashSet<Playlist>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.TimeSpan Duration { get; set; }
        public string Size { get; set; }
        public string FileName { get; set; }
    
        public virtual ICollection<Playlist> Playlists { get; set; }
    }
}
