//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43_Team10A_LibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksDetail
    {
        public BooksDetail()
        {
            this.LoanTransDetails = new HashSet<LoanTransDetail>();
        }
    
        public int BookID { get; set; }
        public string BookTitle { get; set; }
        public string Author { get; set; }
        public string BookType { get; set; }
        public Nullable<long> ISBN { get; set; }
        public Nullable<short> TotalStock { get; set; }
        public Nullable<short> NumberLoaned { get; set; }
    
        public virtual ICollection<LoanTransDetail> LoanTransDetails { get; set; }
    }
}
