//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43_Team10A_LibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanRecord
    {
        public LoanRecord()
        {
            this.LoanTransDetails = new HashSet<LoanTransDetail>();
        }
    
        public int TransactionID { get; set; }
        public int MemberID { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public string Remarks { get; set; }
    
        public virtual MembersDetail MembersDetail { get; set; }
        public virtual ICollection<LoanTransDetail> LoanTransDetails { get; set; }
    }
}
