//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43_Team10A_LibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanTransDetail
    {
        public int TransactionID { get; set; }
        public int BookID { get; set; }
        public Nullable<System.DateTime> DateActualReturn { get; set; }
        public string LoanStatus { get; set; }
    
        public virtual BooksDetail BooksDetail { get; set; }
        public virtual LoanRecord LoanRecord { get; set; }
    }
}
