//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43_Team10A_LibrarySystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SA43_Team10A_LibrarySystemEntities : DbContext
    {
        public SA43_Team10A_LibrarySystemEntities()
            : base("name=SA43_Team10A_LibrarySystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BooksDetail> BooksDetails { get; set; }
        public virtual DbSet<EmpCredential> EmpCredentials { get; set; }
        public virtual DbSet<EmployeesDetail> EmployeesDetails { get; set; }
        public virtual DbSet<LoanRecord> LoanRecords { get; set; }
        public virtual DbSet<LoanTransDetail> LoanTransDetails { get; set; }
        public virtual DbSet<MembersDetail> MembersDetails { get; set; }
    }
}
