//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Property
{
    public int PropertyID { get; set; }
    public string UserName { get; set; }
    public string PropertyName { get; set; }
    public string Address { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<decimal> FloorSize { get; set; }
    public string Type { get; set; }
    public string ImagePath { get; set; }
    public Nullable<int> NoOfBathRoom { get; set; }
    public Nullable<int> NoOfRoom { get; set; }
    public string Description { get; set; }
    public Nullable<decimal> Price { get; set; }
    public Nullable<decimal> Tenure { get; set; }
    public string NearByFacility { get; set; }
    public string Developer { get; set; }
}
